sudo: required
group: travis_latest
language: cpp
os:
  - linux

compiler:
  - gcc

env:
  matrix:
  global:
    - MADARA_ROOT=$TRAVIS_BUILD_DIR/madara
    - GAMS_ROOT=$TRAVIS_BUILD_DIR/gams
    - MPC_ROOT=$TRAVIS_BUILD_DIR/MPC
    - LD_LIBRARY_PATH=$MADARA_ROOT/lib:$GAMS_ROOT/lib:$LD_LIBRARY_PATH
    - CORES=6

matrix:
  include:
    - compiler: clang
      env: CLANG="clang"
      os: osx
    - compiler: gcc
      os: linux
      env: CLANG=""
    - compiler: clang
      env: CLANG="clang"
      os: linux
    - compiler: gcc
      os: linux
      env: CLANG="" SSL="ssl"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - git-core

before_install:
  - git clone -b aceless --single-branch https://github.com/jredmondson/gams $GAMS_ROOT

branches:
  only:
    - master

before_script:
  - export
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export OS=linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OS=mac; fi

script:
  - echo $GAMS_ROOT/scripts/$OS/base_build.sh prereqs $CLANG madara gams tests $SSL
  - $GAMS_ROOT/scripts/$OS/base_build.sh prereqs $CLANG madara gams tests $SSL


